server {
    listen       80 default_server;
    server_name  localhost;

    # pass uri starts with /json to the json-server (validate jwt and removing /json prefix)
    location /json {
        auth_jwt "Protected API";
        auth_jwt_key_file /etc/nginx/conf.d/keys.json;
        rewrite ^/json/(.*)$ /$1 break;
        proxy_pass http://10.10.10.4:3000;
    }

    # custom 401 page for json-style response
    error_page  401   /401.html;
    location = /401.html {
        return 401 "{\"status\": 401, \"message\": \"Unauthorized\"}\n";
    }

    # pass the PHP scripts to Apache-PHP server
    # contain login.php file to generate jwt from any username/password
    # and access.php to send test request with JWT
    location ~ \.php$ {
        proxy_set_header Host            $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_pass http://10.10.10.3;
    }

    # anything else, just redirect to the login.php
    location / {
      return 302 $scheme://$host/login.php;
    }
}

